//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibrarySite.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class copy
    {
        public copy()
        {
            this.loanhists = new HashSet<loanhist>();
        }

        public int isbn { get; set; }
        public short copy_no { get; set; }
        public int title_no { get; set; }
        [Display(Name = "On Loan")]
        public string on_loan { get; set; }

        public virtual item item { get; set; }
        public virtual title title { get; set; }
        public virtual loan loan { get; set; }
        public virtual ICollection<loanhist> loanhists { get; set; }
    }
}

