//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibrarySite.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class juvenile
    {
        [Display(Name = "Member No.")]
        public short member_no { get; set; }

        [Display(Name = "Adult Member")]
        [Required(ErrorMessage = "Adult Member Number is required.")]
        public short adult_member_no { get; set; }


        [Display(Name = "Birth Date")]
        [Required(ErrorMessage = "Birth Date is required.")]
        //[DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime birth_date { get; set; }

        public virtual adult adult { get; set; }
        public virtual member member { get; set; }
    }
}

