//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibrarySite.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class loan
    {
        public loan()
        {
            out_date = DateTime.Now;
            due_date = out_date.AddDays(14);
        }

        [Display(Name = "ISBN")]
        [Required]
        public int isbn { get; set; }
        [Display(Name = "Copy No.")]
        [Required]
        public short copy_no { get; set; }
        [Required]
        public int title_no { get; set; }
        [Required]
        public short member_no { get; set; }
        [Display(Name = "Out Date")]
        [Required]
        public System.DateTime out_date { get; set; }
        [Display(Name = "Due Date")]
        [Required]
        public System.DateTime due_date { get; set; }
        [Display(Name = "Description")]
        public string description { get; set; }
        public string on_load { get; set; }

        public virtual copy copy { get; set; }
        public virtual member member { get; set; }
        public virtual title title { get; set; }
    }
}
