//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibrarySite.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class member
    {
        public member()
        {
            this.loans = new HashSet<loan>();
            this.reservations = new HashSet<reservation>();
        }

        [Display(Name = "Member No.")]
        public short member_no { get; set; }

        [Display(Name = "Last Name")]
        [Required(ErrorMessage = "Last Name is required.")]
        [StringLength(15, ErrorMessage = "Last Name should be 15 or less chars.")]
        public string lastname { get; set; }

        [Display(Name = "First Name")]
        [Required(ErrorMessage = "First Name is required.")]
        [StringLength(15, ErrorMessage = "First Name should be 15 or less chars.")]
        public string firstname { get; set; }

        [Display(Name = "Middle Initial")]
        [StringLength(1, ErrorMessage = "Middle Initial length should be 1 character.")]
        public string middleinitial { get; set; }

        [Display(Name = "Photograph")]
        public byte[] photograph { get; set; }

        [Display(Name = "Member Type")]
        public string member_type { get { return adult != null ? "Adult" : "Juvenile"; } }

        public virtual adult adult { get; set; }
        public virtual juvenile juvenile { get; set; }
        public virtual ICollection<loan> loans { get; set; }
        public virtual ICollection<reservation> reservations { get; set; }
    }
}