//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibrarySite.Data.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class adult
    {
        public adult()
        {
            this.juveniles = new HashSet<juvenile>();
        }
    
        public short member_no { get; set; }
        public string street { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string zip { get; set; }
        public string phone_no { get; set; }
        public System.DateTime expr_date { get; set; }
    
        public virtual member member { get; set; }
        public virtual ICollection<juvenile> juveniles { get; set; }
    }
}
