//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibrarySite.Data.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class item
    {
        public item()
        {
            this.copies = new HashSet<copy>();
            this.reservations = new HashSet<reservation>();
        }
    
        public int isbn { get; set; }
        public int title_no { get; set; }
        public string translation { get; set; }
        public string cover { get; set; }
        public string loanable { get; set; }
    
        public virtual ICollection<copy> copies { get; set; }
        public virtual title title { get; set; }
        public virtual ICollection<reservation> reservations { get; set; }
    }
}
