//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibrarySite.Data.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class juvenile
    {
        public short member_no { get; set; }
        public short adult_member_no { get; set; }
        public System.DateTime birth_date { get; set; }
    
        public virtual adult adult { get; set; }
        public virtual member member { get; set; }
    }
}
