//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibrarySite.Data.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class title
    {
        public title()
        {
            this.copies = new HashSet<copy>();
            this.items = new HashSet<item>();
            this.loans = new HashSet<loan>();
            this.loanhists = new HashSet<loanhist>();
        }
    
        public int title_no { get; set; }
        public string title1 { get; set; }
        public string author { get; set; }
        public string synopsis { get; set; }
    
        public virtual ICollection<copy> copies { get; set; }
        public virtual ICollection<item> items { get; set; }
        public virtual ICollection<loan> loans { get; set; }
        public virtual ICollection<loanhist> loanhists { get; set; }
    }
}
